import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ClientSideProvider } from "@/components/providers/client-side-provider";
import { NavbarActions } from "@/components/navbar-actions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Carichiamo il provider solo sul client
// const NeonAuthProvider = dynamic(
//   () => import("@/components/providers/neon-auth-provider"),
//   { ssr: false }
// );

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <ClientSideProvider>
          <header className="border-b border-gray-200 dark:border-gray-800">
            <div className="mx-auto flex h-16 w-full max-w-7xl items-center justify-between px-4">
              <Link href={"/"} className="text-3xl "><span className="text-purple-500 ">MyEvent</span>Planner</Link>

            {/* Usa NavbarActions invece di scrivere il nav qui direttamente */}
              <NavbarActions /> 
          </div>
        </header>

        <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col px-4 py-6">
          {children}
        </main>
        </ClientSideProvider>
      </body>
    </html>
  );
}
